function [ logOut ]=faces_block(pres,track,log,vars,varNames,curSample)

% fold variable names and values into a struct for ease of
% access/readability
design=cell2struct(vars,varNames,2);
design.BlockNo=curSample;

% DESIGN
trials=ECKList;
trials.Name='face erp/gamma/variability trial list';
trials.Presenter=pres;
trials.Tracker=track;
trials.Log=log;

trials.Table={...
    'Nested',   'Function',     'Fixation', 'Face'              'Orientation'   'FixEEGCode',   'FaceEEGCode'   ;...
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...  
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...  
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'UPRIGHT'       222,            223             ;...  
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;...     
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;... 
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;...    
    1,          'faces_trial',  'ICON',     'caucasian.bmp',    'INVERTED'      222,            226             ;...     
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'UPRIGHT'       222,            224             ;...      
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...  
    1,          'faces_trial',  'ICON',     'asian.bmp',        'INVERTED'      222,            227             ;...      
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'UPRIGHT'       222,            225             ;...      
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             ;...      
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             ;...  
    1,          'faces_trial',  'ICON',     'african.bmp',      'INVERTED'      222,            228             };

trials.ImportVariables(varNames, vars, 'faces_block');
trials.NumSamples=design.NumTrials;
trials.StartSample=design.StartTrial;
trials.Order='RANDOM';

trials.Start();

logOut=[];
end